export class Fee {
  constructor(public LId: number,
              public FGId: number,
              public Id: number,
              public Name: string,
              public BeginDate: any,
              public EndDate: any,
              public BeginTime: any,
              public EndTime: any,
              public Sun: boolean,
              public Mon: boolean,
              public Tue: boolean,
              public Wed: boolean,
              public Thu: boolean,
              public Fri: boolean,
              public Sat: boolean,
              public Hol: boolean,
              public MinDur: number,
              public MaxDur: number,
              public IncDur: number,
              public FeeAmt: number,
              public Enabled: boolean,
              public MinUsers: number,
              public MaxUsers: number,
              public PerUser: boolean,
              public AlwaysInc: boolean,
              public FlatRate: boolean) {}
}
